### ISSUE TITLE
Maintain changelog / releases

### ISSUE THREAD

**Issue by SamuelMS** [frontapp/front-chat-sdk#14]
Hey folks,

Would you consider maintaining a `CHANGELOG` – or even better, cut [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) as developer-facing changes roll out?

As it stands, we have to read through commit history or risk breaking changes anytime we pin the repository to a new commit (see #10 for context). Adds a lot of risk to our organization.

Thank you.

**Comment by Vilos92** [comment]
Hey @SamuelMS ,

I'm sorry for the delayed response, our team has been heads-down on several things recently.

We had not intended for this repository to be used directly in other projects, so we did not implement a `CHANGELOG` nor have a process for cutting releases. Our expectations at the beginning were that the examples provided would be copied/modified to suit the needs of whoever needs them.

That said, I want to acknowledge that there appears to be a demand for some kind of `front-chat-sdk` package, whether it be here or (as you've alluded to in the other issue) published as an npm package.

We will keep this in mind as we deploy changes in the future, and I will surface this issue to the broader team for further discussion.

**Comment by Vilos92** [comment]
Thank you again for the suggestion @SamuelMS, releases can now be seen here: https://github.com/frontapp/front-chat-sdk/releases

Your suggested changes to drop `private: true` has been accounted for in: https://github.com/frontapp/front-chat-sdk/releases/tag/v1.0.1

**Comment by Vilos92** [comment]
Closing as we are now cutting releases for this repository.

**Comment by SamuelMS** [comment]
> Thank you again for the suggestion @SamuelMS, releases can now be seen here: https://github.com/frontapp/front-chat-sdk/releases
> 
> Your suggested changes to drop `private: true` has been accounted for in: https://github.com/frontapp/front-chat-sdk/releases/tag/v1.0.1

Thanks for doing both of these! We'll cut over our projects to use the new releases. Much appreciated.
