### ISSUE TITLE
Embedded Front Chat  not working in Chrome

### ISSUE THREAD

**Issue by gregauger** [frontapp/front-chat-sdk#17]
From my testing, `examples/react-embed-front-chat/index.tsx` doesn't work in Chrome. However it does in Firefox. Adding a console.log to onLoadIframe indicates that this block is not executing. I am not sure of the cause of this.

However I have attached a patch that I believe resolves the issue.

[0001-Remove-use-of-onLoadIframe.patch](https://github.com/user-attachments/files/17047209/0001-Remove-use-of-onLoadIframe.patch)

**Comment by cjmckee** [comment]
Thank you @gregauger 👍 this is now resolved.
